# Generated by Django 2.1.7 on 2019-04-16 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.TextField(max_length=20)),
                ('contact', models.TextField(max_length=20)),
                ('state', models.TextField(max_length=20)),
                ('city', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('postal', models.TextField(max_length=5)),
                ('name', models.TextField(blank=True, max_length=100)),
                ('beds', models.TextField(max_length=10)),
                ('baths', models.TextField(max_length=10)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('unit', models.TextField(blank=True)),
                ('lease_length', models.TextField(blank=True, max_length=20)),
                ('available', models.TextField(blank=True, max_length=20)),
                ('desciption', models.TextField(blank=True)),
                ('Amenities', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
