# Generated by Django 2.1.7 on 2019-04-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
