# Generated by Django 2.1.7 on 2019-04-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190429_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
